# Generated by Django 4.2 on 2023-04-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('online_order', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('flavor_notes', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('coffee_name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=50)),
                ('beverage_type', models.CharField(max_length=20)),
                ('roaster', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comment', models.CharField(max_length=1000)),
                ('sweet', models.IntegerField()),
                ('acidic', models.IntegerField()),
                ('floral', models.IntegerField()),
                ('citrus', models.IntegerField()),
                ('berry', models.IntegerField()),
                ('chocolate', models.IntegerField()),
                ('caramel', models.IntegerField()),
                ('smoky', models.IntegerField()),
                ('bitter', models.IntegerField()),
                ('clean', models.IntegerField()),
                ('shops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes_api.shops')),
            ],
        ),
    ]
