# Generated by Django 4.2 on 2023-04-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes_api', '0003_alter_shops_best_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='best_type',
        ),
    ]
